# Generated by Django 3.1 on 2021-02-08 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField(max_length=50)),
                ('workupdate', models.CharField(max_length=500)),
                ('githublink', models.CharField(max_length=200)),
            ],
        ),
    ]
