# Generated by Django 3.1 on 2021-02-08 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='image1',
            field=models.ImageField(default='', upload_to='student/images'),
        ),
        migrations.AlterField(
            model_name='student',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='workupdate',
            field=models.CharField(max_length=800),
        ),
    ]
