# Generated by Django 3.1 on 2021-02-08 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0002_auto_20210208_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='image2',
            field=models.ImageField(default='', upload_to='student/images'),
        ),
        migrations.AddField(
            model_name='student',
            name='image3',
            field=models.ImageField(default='', upload_to='student/images'),
        ),
        migrations.AddField(
            model_name='student',
            name='image4',
            field=models.ImageField(default='', upload_to='student/images'),
        ),
        migrations.AddField(
            model_name='student',
            name='image5',
            field=models.ImageField(default='', upload_to='student/images'),
        ),
        migrations.AddField(
            model_name='student',
            name='technologiesUsed',
            field=models.CharField(default='', max_length=200),
        ),
    ]
