# Generated by Django 3.1 on 2021-02-08 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0003_auto_20210208_2238'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technologies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='technologiesUsed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_register.technologies'),
        ),
    ]
