# Generated by Django 3.1 on 2021-02-08 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0005_remove_student_technologiesused'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Technologies',
        ),
    ]
