# Generated by Django 3.1 on 2021-02-08 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0006_delete_technologies'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technologies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TechnologyUsed', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
