# Generated by Django 3.1 on 2021-02-08 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0007_technologies'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='technologiesUsed',
            field=models.ManyToManyField(related_name='entry', to='login_register.Technologies'),
        ),
    ]
