# Generated by Django 3.1.6 on 2021-02-09 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0008_student_technologiesused'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='image5',
        ),
    ]
